# Generated by Django 5.0.7 on 2025-04-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='photo_path',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='sale',
            name='promocode',
            field=models.CharField(max_length=20, null=True, verbose_name='Промокод'),
        ),
    ]
