# Generated by Django 5.0.7 on 2025-04-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_rename_photo_path_category_photo_sale_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='uploads/', verbose_name='Фото'),
        ),
    ]
