# Generated by Django 5.0.7 on 2025-04-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_alter_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='subtitle',
            field=models.CharField(max_length=30, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='uploads/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Заголовок'),
        ),
    ]
