# Generated by Django 5.0.7 on 2025-04-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_sale_subtitle_alter_category_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='promocode',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='subtitle',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Подзаголовок'),
        ),
    ]
