# Generated by Django 5.0.7 on 2025-04-23 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0006_alter_sale_promocode_alter_sale_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='media/', verbose_name='Фото'),
        ),
    ]
