# Generated by Django 5.0.7 on 2025-04-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0007_alter_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='static/media/', verbose_name='Фото'),
        ),
    ]
