# Generated by Django 5.0.7 on 2025-04-23 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0008_alter_category_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/media/', verbose_name='Фото'),
        ),
    ]
