# Generated by Django 5.0.7 on 2025-04-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0009_sale_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
