# Generated by Django 5.0.7 on 2025-04-23 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0010_sale_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billboard.category', verbose_name='Категория'),
        ),
    ]
