# Generated by Django 5.0.7 on 2025-04-28 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0011_alter_sale_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['id'], 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
    ]
