# Generated by Django 5.0.7 on 2025-04-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0013_alter_sale_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='http://127.0.0.1:8000/static/media/clothes.png', null=True, upload_to='static/media/', verbose_name='Фото'),
        ),
    ]
