# Generated by Django 5.0.7 on 2025-05-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0016_alter_category_photo_alter_sale_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='subtitle',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
    ]
